### ISSUE TITLE
Trying to add RIVA/GeForce SVGA

### ISSUE THREAD

**Issue by aquaboxs** [aquaboxs/dosbox-x#1]
After in year on 2020, someone wants to add 3D accelerators like the Savage series, Riva series (RIVA 128, RIVA TNT, and RIVA TNT2), and (if possible) GeForce series (early 2000?)

I found this nVIDIA Registers List from hackipedia.org: http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20IBM%20compatible/Video/VGA/SVGA/nVidia/nVidia%20register%20list%20%282010%2d02%2d02%29%2exml

 I think I'll create it, let's start a simple SVGA such as `machine=svga_nv_riva128` and `machine=svga_nv_geforce`, and then PCI Bus would be called `nVIDIA = 10de`, and `SGS Thomson nVIDIA = 12d2`.

**Comment by aquaboxs** [comment]
Done, I think svga_nv_riva128 needs fix up, but It needs I2C/DDC. but whatever, it's okay.

**Comment by Torinde** [comment]
Do you plan to make a PR to upstream your Riva128 and Voodoo3 additions to DOSbox-X?

Also, FYI - 86Box/PCBox have also Riva128, maybe useful to compare your implementation with thiers: https://github.com/PCBox/PCBox/issues/34
